use temp file in local directory (as autoconf does) rather than in tmp

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.44 .
+# From configure.in Revision: 1.45 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.
 #
@@ -10394,20 +10394,18 @@ cat >>confdefs.h <<EOF
 #define PATH_SEPARATOR "$PATH_SEPARATOR"
 EOF
 
-echo "$as_me:10397: checking for errno
-value of second connect to refused port" >&5
-echo $ECHO_N "checking for errno
-value of second connect to refused port... $ECHO_C" >&6
+echo "$as_me:10397: checking errno value of second connect to refused port" >&5
+echo $ECHO_N "checking errno value of second connect to refused port... $ECHO_C" >&6
 if test "${ac_cv_second_connect_errno+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   if test "$cross_compiling" = yes; then
-  { { echo "$as_me:10405: error: cannot run test program while cross compiling" >&5
+  { { echo "$as_me:10403: error: cannot run test program while cross compiling" >&5
 echo "$as_me: error: cannot run test program while cross compiling" >&2;}
    { (exit 1); exit 1; }; }
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 10410 "configure"
+#line 10408 "configure"
 #include "confdefs.h"
 
 #include <stdio.h>
@@ -10455,23 +10453,23 @@ main(int argc, char **argv)
   if (connect(s, (struct sockaddr *)(&sin), sizeof(sin)) == 0)
     exit(5);
 
-  snprintf(buf,sizeof(buf),"echo %d >/tmp/errno", errno);
+  snprintf(buf,sizeof(buf),"echo %d > .errno", errno);
   system(buf);
   exit(0);
 }
 _ACEOF
 rm -f conftest$ac_exeext
-if { (eval echo "$as_me:10464: \"$ac_link\"") >&5
+if { (eval echo "$as_me:10462: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:10467: \$? = $ac_status" >&5
+  echo "$as_me:10465: \$? = $ac_status" >&5
   (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
-  { (eval echo "$as_me:10469: \"$ac_try\"") >&5
+  { (eval echo "$as_me:10467: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:10472: \$? = $ac_status" >&5
+  echo "$as_me:10470: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-   ac_cv_second_connect_errno=`cat /tmp/errno`; rm /tmp/errno
+   ac_cv_second_connect_errno=`cat .errno`; rm .errno
 else
   echo "$as_me: program exited with status $ac_status" >&5
 echo "$as_me: failed program was:" >&5
@@ -10480,7 +10478,7 @@ fi
 rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
-echo "$as_me:10483: result: $ac_cv_second_connect_errno" >&5
+echo "$as_me:10481: result: $ac_cv_second_connect_errno" >&5
 echo "${ECHO_T}$ac_cv_second_connect_errno" >&6
 if test "X$ac_cv_second_connect_errno" != "X"
 then
@@ -10573,7 +10571,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:10576: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:10574: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -10751,7 +10749,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:10754: error: ambiguous option: $1
+    { { echo "$as_me:10752: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -10770,7 +10768,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:10773: error: unrecognized option: $1
+  -*) { { echo "$as_me:10771: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -10807,7 +10805,7 @@ do
   # Handling of arguments.
   "Make.config" ) CONFIG_FILES="$CONFIG_FILES Make.config" ;;
   "libbk_autoconf.h" ) CONFIG_HEADERS="$CONFIG_HEADERS libbk_autoconf.h" ;;
-  *) { { echo "$as_me:10810: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:10808: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -11069,7 +11067,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:11072: creating $ac_file" >&5
+    { echo "$as_me:11070: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -11087,7 +11085,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:11090: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:11088: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -11100,7 +11098,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:11103: error: cannot find input file: $f" >&5
+           { { echo "$as_me:11101: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -11161,7 +11159,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:11164: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:11162: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -11172,7 +11170,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:11175: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:11173: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -11185,7 +11183,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:11188: error: cannot find input file: $f" >&5
+           { { echo "$as_me:11186: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -11302,7 +11300,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:11305: $ac_file is unchanged" >&5
+      { echo "$as_me:11303: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
