Added javadoc target for developer convenience.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13273,9 +13273,47 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+# Extract the first word of "javadoc", so it can be a program name with args.
+set dummy javadoc; ac_word=$2
+echo "$as_me:13278: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_JAVADOC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $JAVADOC in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_JAVADOC="$JAVADOC" # Let the user override the test with a path.
+  ;;
+  *)
+  ac_save_IFS=$IFS; IFS=$ac_path_separator
+ac_dummy="/usr/local/java/jdk/bin:$PATH:/usr/java/jdk/bin"
+for ac_dir in $ac_dummy; do
+  IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  if $as_executable_p "$ac_dir/$ac_word"; then
+   ac_cv_path_JAVADOC="$ac_dir/$ac_word"
+   echo "$as_me:13295: found $ac_dir/$ac_word" >&5
+   break
+fi
+done
+
+  test -z "$ac_cv_path_JAVADOC" && ac_cv_path_JAVADOC="$FALSE"
+  ;;
+esac
+fi
+JAVADOC=$ac_cv_path_JAVADOC
+
+if test -n "$JAVADOC"; then
+  echo "$as_me:13307: result: $JAVADOC" >&5
+echo "${ECHO_T}$JAVADOC" >&6
+else
+  echo "$as_me:13310: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
 # Extract the first word of "jhindexer", so it can be a program name with args.
 set dummy jhindexer; ac_word=$2
-echo "$as_me:13278: checking for $ac_word" >&5
+echo "$as_me:13316: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_JHINDEXER+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13292,7 +13330,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_JHINDEXER="$ac_dir/$ac_word"
-   echo "$as_me:13295: found $ac_dir/$ac_word" >&5
+   echo "$as_me:13333: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -13304,16 +13342,16 @@ fi
 JHINDEXER=$ac_cv_path_JHINDEXER
 
 if test -n "$JHINDEXER"; then
-  echo "$as_me:13307: result: $JHINDEXER" >&5
+  echo "$as_me:13345: result: $JHINDEXER" >&5
 echo "${ECHO_T}$JHINDEXER" >&6
 else
-  echo "$as_me:13310: result: no" >&5
+  echo "$as_me:13348: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "doxygen", so it can be a program name with args.
 set dummy doxygen; ac_word=$2
-echo "$as_me:13316: checking for $ac_word" >&5
+echo "$as_me:13354: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_DOXYGEN+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13330,7 +13368,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_DOXYGEN="$ac_dir/$ac_word"
-   echo "$as_me:13333: found $ac_dir/$ac_word" >&5
+   echo "$as_me:13371: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -13342,16 +13380,16 @@ fi
 DOXYGEN=$ac_cv_path_DOXYGEN
 
 if test -n "$DOXYGEN"; then
-  echo "$as_me:13345: result: $DOXYGEN" >&5
+  echo "$as_me:13383: result: $DOXYGEN" >&5
 echo "${ECHO_T}$DOXYGEN" >&6
 else
-  echo "$as_me:13348: result: no" >&5
+  echo "$as_me:13386: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "dot", so it can be a program name with args.
 set dummy dot; ac_word=$2
-echo "$as_me:13354: checking for $ac_word" >&5
+echo "$as_me:13392: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_HAVE_DOT+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13366,7 +13404,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_HAVE_DOT="YES"
-echo "$as_me:13369: found $ac_dir/$ac_word" >&5
+echo "$as_me:13407: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -13375,10 +13413,10 @@ fi
 fi
 HAVE_DOT=$ac_cv_prog_HAVE_DOT
 if test -n "$HAVE_DOT"; then
-  echo "$as_me:13378: result: $HAVE_DOT" >&5
+  echo "$as_me:13416: result: $HAVE_DOT" >&5
 echo "${ECHO_T}$HAVE_DOT" >&6
 else
-  echo "$as_me:13381: result: no" >&5
+  echo "$as_me:13419: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -13386,7 +13424,7 @@ for ac_prog in browser netscape konqueror mozilla iexplore.exe lynx
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:13389: checking for $ac_word" >&5
+echo "$as_me:13427: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_BROWSER+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13403,7 +13441,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_BROWSER="$ac_dir/$ac_word"
-   echo "$as_me:13406: found $ac_dir/$ac_word" >&5
+   echo "$as_me:13444: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -13414,10 +13452,10 @@ fi
 BROWSER=$ac_cv_path_BROWSER
 
 if test -n "$BROWSER"; then
-  echo "$as_me:13417: result: $BROWSER" >&5
+  echo "$as_me:13455: result: $BROWSER" >&5
 echo "${ECHO_T}$BROWSER" >&6
 else
-  echo "$as_me:13420: result: no" >&5
+  echo "$as_me:13458: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -13427,7 +13465,7 @@ test -n "$BROWSER" || BROWSER="$FALSE"
 
 # Extract the first word of "xref", so it can be a program name with args.
 set dummy xref; ac_word=$2
-echo "$as_me:13430: checking for $ac_word" >&5
+echo "$as_me:13468: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_XREF+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13444,7 +13482,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_XREF="$ac_dir/$ac_word"
-   echo "$as_me:13447: found $ac_dir/$ac_word" >&5
+   echo "$as_me:13485: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -13456,16 +13494,16 @@ fi
 XREF=$ac_cv_path_XREF
 
 if test -n "$XREF"; then
-  echo "$as_me:13459: result: $XREF" >&5
+  echo "$as_me:13497: result: $XREF" >&5
 echo "${ECHO_T}$XREF" >&6
 else
-  echo "$as_me:13462: result: no" >&5
+  echo "$as_me:13500: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 if test "$ac_cv_search_gethostbyname2" = "no"
 then
-  { echo "$as_me:13468: WARNING: you will not be able to resolve IPv6 names" >&5
+  { echo "$as_me:13506: WARNING: you will not be able to resolve IPv6 names" >&5
 echo "$as_me: WARNING: you will not be able to resolve IPv6 names" >&2;}
 fi
 
@@ -13579,7 +13617,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:13582: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:13620: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -13757,7 +13795,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:13760: error: ambiguous option: $1
+    { { echo "$as_me:13798: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -13776,7 +13814,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:13779: error: unrecognized option: $1
+  -*) { { echo "$as_me:13817: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -13814,7 +13852,7 @@ do
   "Make.config" ) CONFIG_FILES="$CONFIG_FILES Make.config" ;;
   "getcwd.sh" ) CONFIG_FILES="$CONFIG_FILES getcwd.sh" ;;
   "libbk_autoconf.h" ) CONFIG_HEADERS="$CONFIG_HEADERS libbk_autoconf.h" ;;
-  *) { { echo "$as_me:13817: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:13855: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -13968,6 +14006,7 @@ s,@BGCC@,$BGCC,;t t
 s,@INSURE@,$INSURE,;t t
 s,@JAVAC@,$JAVAC,;t t
 s,@JAR@,$JAR,;t t
+s,@JAVADOC@,$JAVADOC,;t t
 s,@JHINDEXER@,$JHINDEXER,;t t
 s,@DOXYGEN@,$DOXYGEN,;t t
 s,@HAVE_DOT@,$HAVE_DOT,;t t
@@ -14089,7 +14128,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:14092: creating $ac_file" >&5
+    { echo "$as_me:14131: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -14107,7 +14146,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:14110: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:14149: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -14120,7 +14159,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:14123: error: cannot find input file: $f" >&5
+           { { echo "$as_me:14162: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -14181,7 +14220,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:14184: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:14223: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -14192,7 +14231,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:14195: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:14234: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -14205,7 +14244,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:14208: error: cannot find input file: $f" >&5
+           { { echo "$as_me:14247: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -14322,7 +14361,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:14325: $ac_file is unchanged" >&5
+      { echo "$as_me:14364: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
