support for bounds checking gcc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9806,11 +9806,87 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+# Extract the first word of "bgcc", so it can be a program name with args.
+set dummy bgcc; ac_word=$2
+echo "$as_me:9811: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_BGCC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $BGCC in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_BGCC="$BGCC" # Let the user override the test with a path.
+  ;;
+  *)
+  ac_save_IFS=$IFS; IFS=$ac_path_separator
+ac_dummy="$PATH"
+for ac_dir in $ac_dummy; do
+  IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  if $as_executable_p "$ac_dir/$ac_word"; then
+   ac_cv_path_BGCC="$ac_dir/$ac_word"
+   echo "$as_me:9828: found $ac_dir/$ac_word" >&5
+   break
+fi
+done
+
+  test -z "$ac_cv_path_BGCC" && ac_cv_path_BGCC="$FALSE"
+  ;;
+esac
+fi
+BGCC=$ac_cv_path_BGCC
+
+if test -n "$BGCC"; then
+  echo "$as_me:9840: result: $BGCC" >&5
+echo "${ECHO_T}$BGCC" >&6
+else
+  echo "$as_me:9843: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+# Extract the first word of "insure", so it can be a program name with args.
+set dummy insure; ac_word=$2
+echo "$as_me:9849: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_INSURE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $INSURE in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_INSURE="$INSURE" # Let the user override the test with a path.
+  ;;
+  *)
+  ac_save_IFS=$IFS; IFS=$ac_path_separator
+ac_dummy="$PATH:$PARASOFT/bin:/usr/local/parasoft/bin"
+for ac_dir in $ac_dummy; do
+  IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  if $as_executable_p "$ac_dir/$ac_word"; then
+   ac_cv_path_INSURE="$ac_dir/$ac_word"
+   echo "$as_me:9866: found $ac_dir/$ac_word" >&5
+   break
+fi
+done
+
+  test -z "$ac_cv_path_INSURE" && ac_cv_path_INSURE="$FALSE"
+  ;;
+esac
+fi
+INSURE=$ac_cv_path_INSURE
+
+if test -n "$INSURE"; then
+  echo "$as_me:9878: result: $INSURE" >&5
+echo "${ECHO_T}$INSURE" >&6
+else
+  echo "$as_me:9881: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
 # note - don't use $PATH_SEPARATOR in this file; we always use Cygwin make
 
 # Extract the first word of "javac", so it can be a program name with args.
 set dummy javac; ac_word=$2
-echo "$as_me:9813: checking for $ac_word" >&5
+echo "$as_me:9889: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_JAVAC+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -9827,7 +9903,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_JAVAC="$ac_dir/$ac_word"
-   echo "$as_me:9830: found $ac_dir/$ac_word" >&5
+   echo "$as_me:9906: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -9839,16 +9915,16 @@ fi
 JAVAC=$ac_cv_path_JAVAC
 
 if test -n "$JAVAC"; then
-  echo "$as_me:9842: result: $JAVAC" >&5
+  echo "$as_me:9918: result: $JAVAC" >&5
 echo "${ECHO_T}$JAVAC" >&6
 else
-  echo "$as_me:9845: result: no" >&5
+  echo "$as_me:9921: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "jar", so it can be a program name with args.
 set dummy jar; ac_word=$2
-echo "$as_me:9851: checking for $ac_word" >&5
+echo "$as_me:9927: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_JAR+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -9865,7 +9941,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_JAR="$ac_dir/$ac_word"
-   echo "$as_me:9868: found $ac_dir/$ac_word" >&5
+   echo "$as_me:9944: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -9877,16 +9953,16 @@ fi
 JAR=$ac_cv_path_JAR
 
 if test -n "$JAR"; then
-  echo "$as_me:9880: result: $JAR" >&5
+  echo "$as_me:9956: result: $JAR" >&5
 echo "${ECHO_T}$JAR" >&6
 else
-  echo "$as_me:9883: result: no" >&5
+  echo "$as_me:9959: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "jhindexer", so it can be a program name with args.
 set dummy jhindexer; ac_word=$2
-echo "$as_me:9889: checking for $ac_word" >&5
+echo "$as_me:9965: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_JHINDEXER+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -9903,7 +9979,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_JHINDEXER="$ac_dir/$ac_word"
-   echo "$as_me:9906: found $ac_dir/$ac_word" >&5
+   echo "$as_me:9982: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -9915,16 +9991,16 @@ fi
 JHINDEXER=$ac_cv_path_JHINDEXER
 
 if test -n "$JHINDEXER"; then
-  echo "$as_me:9918: result: $JHINDEXER" >&5
+  echo "$as_me:9994: result: $JHINDEXER" >&5
 echo "${ECHO_T}$JHINDEXER" >&6
 else
-  echo "$as_me:9921: result: no" >&5
+  echo "$as_me:9997: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "doxygen", so it can be a program name with args.
 set dummy doxygen; ac_word=$2
-echo "$as_me:9927: checking for $ac_word" >&5
+echo "$as_me:10003: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_DOXYGEN+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -9941,7 +10017,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_DOXYGEN="$ac_dir/$ac_word"
-   echo "$as_me:9944: found $ac_dir/$ac_word" >&5
+   echo "$as_me:10020: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -9953,16 +10029,16 @@ fi
 DOXYGEN=$ac_cv_path_DOXYGEN
 
 if test -n "$DOXYGEN"; then
-  echo "$as_me:9956: result: $DOXYGEN" >&5
+  echo "$as_me:10032: result: $DOXYGEN" >&5
 echo "${ECHO_T}$DOXYGEN" >&6
 else
-  echo "$as_me:9959: result: no" >&5
+  echo "$as_me:10035: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "dot", so it can be a program name with args.
 set dummy dot; ac_word=$2
-echo "$as_me:9965: checking for $ac_word" >&5
+echo "$as_me:10041: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_HAVE_DOT+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -9977,7 +10053,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_HAVE_DOT="YES"
-echo "$as_me:9980: found $ac_dir/$ac_word" >&5
+echo "$as_me:10056: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -9986,10 +10062,10 @@ fi
 fi
 HAVE_DOT=$ac_cv_prog_HAVE_DOT
 if test -n "$HAVE_DOT"; then
-  echo "$as_me:9989: result: $HAVE_DOT" >&5
+  echo "$as_me:10065: result: $HAVE_DOT" >&5
 echo "${ECHO_T}$HAVE_DOT" >&6
 else
-  echo "$as_me:9992: result: no" >&5
+  echo "$as_me:10068: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -9997,7 +10073,7 @@ for ac_prog in browser netscape konqueror mozilla iexplore.exe lynx
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:10000: checking for $ac_word" >&5
+echo "$as_me:10076: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_BROWSER+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -10014,7 +10090,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_BROWSER="$ac_dir/$ac_word"
-   echo "$as_me:10017: found $ac_dir/$ac_word" >&5
+   echo "$as_me:10093: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -10025,10 +10101,10 @@ fi
 BROWSER=$ac_cv_path_BROWSER
 
 if test -n "$BROWSER"; then
-  echo "$as_me:10028: result: $BROWSER" >&5
+  echo "$as_me:10104: result: $BROWSER" >&5
 echo "${ECHO_T}$BROWSER" >&6
 else
-  echo "$as_me:10031: result: no" >&5
+  echo "$as_me:10107: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -10038,7 +10114,7 @@ test -n "$BROWSER" || BROWSER="$FALSE"
 
 # Extract the first word of "ar", so it can be a program name with args.
 set dummy ar; ac_word=$2
-echo "$as_me:10041: checking for $ac_word" >&5
+echo "$as_me:10117: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_AR+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -10055,7 +10131,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_AR="$ac_dir/$ac_word"
-   echo "$as_me:10058: found $ac_dir/$ac_word" >&5
+   echo "$as_me:10134: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -10066,10 +10142,10 @@ fi
 AR=$ac_cv_path_AR
 
 if test -n "$AR"; then
-  echo "$as_me:10069: result: $AR" >&5
+  echo "$as_me:10145: result: $AR" >&5
 echo "${ECHO_T}$AR" >&6
 else
-  echo "$as_me:10072: result: no" >&5
+  echo "$as_me:10148: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -10159,7 +10235,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:10162: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:10238: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -10337,7 +10413,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:10340: error: ambiguous option: $1
+    { { echo "$as_me:10416: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -10356,7 +10432,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:10359: error: unrecognized option: $1
+  -*) { { echo "$as_me:10435: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -10393,7 +10469,7 @@ do
   # Handling of arguments.
   "Make.config" ) CONFIG_FILES="$CONFIG_FILES Make.config" ;;
   "libbk_autoconf.h" ) CONFIG_HEADERS="$CONFIG_HEADERS libbk_autoconf.h" ;;
-  *) { { echo "$as_me:10396: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:10472: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -10527,6 +10603,8 @@ s,@SED@,$SED,;t t
 s,@TEST@,$TEST,;t t
 s,@PERL@,$PERL,;t t
 s,@XML2CONFIG@,$XML2CONFIG,;t t
+s,@BGCC@,$BGCC,;t t
+s,@INSURE@,$INSURE,;t t
 s,@JAVAC@,$JAVAC,;t t
 s,@JAR@,$JAR,;t t
 s,@JHINDEXER@,$JHINDEXER,;t t
@@ -10648,7 +10726,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:10651: creating $ac_file" >&5
+    { echo "$as_me:10729: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -10666,7 +10744,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:10669: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:10747: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -10679,7 +10757,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:10682: error: cannot find input file: $f" >&5
+           { { echo "$as_me:10760: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -10740,7 +10818,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:10743: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:10821: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -10751,7 +10829,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:10754: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:10832: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -10764,7 +10842,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:10767: error: cannot find input file: $f" >&5
+           { { echo "$as_me:10845: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -10881,7 +10959,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:10884: $ac_file is unchanged" >&5
+      { echo "$as_me:10962: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
