Bug 8639: Switch from gettimeofday to clock_gettime
clock_gettime can be found in librt, so librt is probed in autoconf.
clock_gettime uses timespec, but in practice gets usec accuracy.  The
system random number generation time has been restored to nominal
generation time.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -464,7 +464,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX LEX LEXLIB LEX_OUTPUT_ROOT YACC CPP CXXCPP AWK build build_cpu build_vendor build_os host host_cpu host_vendor host_os LIBM HAVE_LIBSSL HAVE_KRB5SUPPORT HAVE_PROJ_POSTGRES ALIGN_FUNCTIONS_SWITCH NO_POINTER_SIGN_WARN EGREP HAVE_OVERZEALOUS_CHAR_SUBSCRIPT BK_SPECIAL_DEBUG BK_NO_STRICT_PROTOTYPES INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S PAWD ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP F77 FFLAGS ac_ct_F77 LIBTOOL shlibpath_var shlibext modulext lt_prog_compiler_static LIBOBJS PTHREAD_CC PTHREAD_LIBS PTHREAD_CFLAGS HAVE_PTHREADS PROFILED_LIBS ALLOCA TRUE FALSE TEST RM TOUCH CP MV MKDIR LS GTAR TAR GZIP CVS GIT GITS UNAME CHMOD JOIN FMT CAT BASENAME SED PERL GREP FIND SORT UNIQ XARGS TEE EXPR XML2CONFIG BGCC PARASOFT INSURE JTEST JAVAC JAR JAVADOC JHINDEXER DOXYGEN HAVE_DOT BROWSER XREF HEAD OINKMASTER ADDSID CREATE_SIDMAP PTHREAD_WITH_BAD_EMPTY_LOOPS ORACLE_HOME HAVE_ORACLE INSTALL_PRESERVE LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX LEX LEXLIB LEX_OUTPUT_ROOT YACC CPP CXXCPP AWK build build_cpu build_vendor build_os host host_cpu host_vendor host_os LIBM HAVE_LIBSSL HAVE_LIBRT RT_LIBS HAVE_KRB5SUPPORT HAVE_PROJ_POSTGRES ALIGN_FUNCTIONS_SWITCH NO_POINTER_SIGN_WARN EGREP HAVE_OVERZEALOUS_CHAR_SUBSCRIPT BK_SPECIAL_DEBUG BK_NO_STRICT_PROTOTYPES INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S PAWD ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP F77 FFLAGS ac_ct_F77 LIBTOOL shlibpath_var shlibext modulext lt_prog_compiler_static LIBOBJS PTHREAD_CC PTHREAD_LIBS PTHREAD_CFLAGS HAVE_PTHREADS PROFILED_LIBS ALLOCA TRUE FALSE TEST RM TOUCH CP MV MKDIR LS GTAR TAR GZIP CVS GIT GITS UNAME CHMOD JOIN FMT CAT BASENAME SED PERL GREP FIND SORT UNIQ XARGS TEE EXPR XML2CONFIG BGCC PARASOFT INSURE JTEST JAVAC JAR JAVADOC JHINDEXER DOXYGEN HAVE_DOT BROWSER XREF HEAD OINKMASTER ADDSID CREATE_SIDMAP PTHREAD_WITH_BAD_EMPTY_LOOPS ORACLE_HOME HAVE_ORACLE INSTALL_PRESERVE LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -4375,6 +4375,85 @@ then
 
 fi
 
+echo "$as_me:$LINENO: checking for clock_gettime in -lrt" >&5
+echo $ECHO_N "checking for clock_gettime in -lrt... $ECHO_C" >&6
+if test "${ac_cv_lib_rt_clock_gettime+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lrt  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char clock_gettime ();
+int
+main ()
+{
+clock_gettime ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_rt_clock_gettime=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_rt_clock_gettime=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_rt_clock_gettime" >&5
+echo "${ECHO_T}$ac_cv_lib_rt_clock_gettime" >&6
+if test $ac_cv_lib_rt_clock_gettime = yes; then
+  /bin/true
+else
+  /bin/true
+fi
+
+if test "$ac_cv_lib_rt_clock_gettime" = yes
+then
+	HAVE_LIBRT=true
+
+	RT_LIBS=-lrt
+
+fi
+
+
 echo "$as_me:$LINENO: checking for krb5int_pthread_loaded in -lkrb5support" >&5
 echo $ECHO_N "checking for krb5int_pthread_loaded in -lkrb5support... $ECHO_C" >&6
 if test "${ac_cv_lib_krb5support_krb5int_pthread_loaded+set}" = set; then
@@ -8117,7 +8196,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 8120 "configure"' > conftest.$ac_ext
+  echo '#line 8199 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8764,7 +8843,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:8767:" \
+echo "$as_me:8846:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -9799,11 +9878,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9802: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9881: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9806: \$? = $ac_status" >&5
+   echo "$as_me:9885: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10031,11 +10110,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10034: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10113: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10038: \$? = $ac_status" >&5
+   echo "$as_me:10117: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10098,11 +10177,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10101: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10180: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10105: \$? = $ac_status" >&5
+   echo "$as_me:10184: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12319,7 +12398,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12322 "configure"
+#line 12401 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12417,7 +12496,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12420 "configure"
+#line 12499 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14657,11 +14736,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14660: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14739: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14664: \$? = $ac_status" >&5
+   echo "$as_me:14743: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -14724,11 +14803,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14727: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14806: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14731: \$? = $ac_status" >&5
+   echo "$as_me:14810: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16155,7 +16234,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 16158 "configure"
+#line 16237 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -16253,7 +16332,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 16256 "configure"
+#line 16335 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -17086,11 +17165,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17089: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17168: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17093: \$? = $ac_status" >&5
+   echo "$as_me:17172: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -17153,11 +17232,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17156: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17235: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17160: \$? = $ac_status" >&5
+   echo "$as_me:17239: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19233,11 +19312,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19236: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19315: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19240: \$? = $ac_status" >&5
+   echo "$as_me:19319: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -19465,11 +19544,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19468: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19547: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19472: \$? = $ac_status" >&5
+   echo "$as_me:19551: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -19532,11 +19611,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19535: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19614: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19539: \$? = $ac_status" >&5
+   echo "$as_me:19618: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21753,7 +21832,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 21756 "configure"
+#line 21835 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21851,7 +21930,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 21854 "configure"
+#line 21933 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -32725,6 +32804,8 @@ s,@host_vendor@,$host_vendor,;t t
 s,@host_os@,$host_os,;t t
 s,@LIBM@,$LIBM,;t t
 s,@HAVE_LIBSSL@,$HAVE_LIBSSL,;t t
+s,@HAVE_LIBRT@,$HAVE_LIBRT,;t t
+s,@RT_LIBS@,$RT_LIBS,;t t
 s,@HAVE_KRB5SUPPORT@,$HAVE_KRB5SUPPORT,;t t
 s,@HAVE_PROJ_POSTGRES@,$HAVE_PROJ_POSTGRES,;t t
 s,@ALIGN_FUNCTIONS_SWITCH@,$ALIGN_FUNCTIONS_SWITCH,;t t
