Once *again* make WANT_INSURE=true work (how does this keep breaking?...) Fix some insight nits.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.78 .
+# From configure.in Revision: 1.79 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.
 #
@@ -13154,9 +13154,23 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+# Look for PARASOFT directory if $PARASOFT is not found
+if test "X$PARASOFT" '=' "X"
+then
+	if test -d /usr/local/parasoft
+	then
+		export PARASOFT="/usr/local/parasoft"
+	fi
+fi
+
+if test \! -d $PARASOFT
+then
+	export PARASOFT=/path/to/nowhere
+fi
+
 # Extract the first word of "insure", so it can be a program name with args.
 set dummy insure; ac_word=$2
-echo "$as_me:13159: checking for $ac_word" >&5
+echo "$as_me:13173: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_INSURE+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13173,7 +13187,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_INSURE="$ac_dir/$ac_word"
-   echo "$as_me:13176: found $ac_dir/$ac_word" >&5
+   echo "$as_me:13190: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -13185,10 +13199,48 @@ fi
 INSURE=$ac_cv_path_INSURE
 
 if test -n "$INSURE"; then
-  echo "$as_me:13188: result: $INSURE" >&5
+  echo "$as_me:13202: result: $INSURE" >&5
 echo "${ECHO_T}$INSURE" >&6
 else
-  echo "$as_me:13191: result: no" >&5
+  echo "$as_me:13205: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+# Extract the first word of "jtest", so it can be a program name with args.
+set dummy jtest; ac_word=$2
+echo "$as_me:13211: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_JTEST+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $JTEST in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_JTEST="$JTEST" # Let the user override the test with a path.
+  ;;
+  *)
+  ac_save_IFS=$IFS; IFS=$ac_path_separator
+ac_dummy="$PATH:$PARASOFT/bin:/usr/local/parasoft/bin"
+for ac_dir in $ac_dummy; do
+  IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  if $as_executable_p "$ac_dir/$ac_word"; then
+   ac_cv_path_JTEST="$ac_dir/$ac_word"
+   echo "$as_me:13228: found $ac_dir/$ac_word" >&5
+   break
+fi
+done
+
+  test -z "$ac_cv_path_JTEST" && ac_cv_path_JTEST="$FALSE"
+  ;;
+esac
+fi
+JTEST=$ac_cv_path_JTEST
+
+if test -n "$JTEST"; then
+  echo "$as_me:13240: result: $JTEST" >&5
+echo "${ECHO_T}$JTEST" >&6
+else
+  echo "$as_me:13243: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -13199,7 +13251,7 @@ fi
 # default for new version testing, though...
 # Extract the first word of "javac", so it can be a program name with args.
 set dummy javac; ac_word=$2
-echo "$as_me:13202: checking for $ac_word" >&5
+echo "$as_me:13254: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_JAVAC+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13216,7 +13268,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_JAVAC="$ac_dir/$ac_word"
-   echo "$as_me:13219: found $ac_dir/$ac_word" >&5
+   echo "$as_me:13271: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -13228,16 +13280,16 @@ fi
 JAVAC=$ac_cv_path_JAVAC
 
 if test -n "$JAVAC"; then
-  echo "$as_me:13231: result: $JAVAC" >&5
+  echo "$as_me:13283: result: $JAVAC" >&5
 echo "${ECHO_T}$JAVAC" >&6
 else
-  echo "$as_me:13234: result: no" >&5
+  echo "$as_me:13286: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "jar", so it can be a program name with args.
 set dummy jar; ac_word=$2
-echo "$as_me:13240: checking for $ac_word" >&5
+echo "$as_me:13292: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_JAR+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13254,7 +13306,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_JAR="$ac_dir/$ac_word"
-   echo "$as_me:13257: found $ac_dir/$ac_word" >&5
+   echo "$as_me:13309: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -13266,16 +13318,16 @@ fi
 JAR=$ac_cv_path_JAR
 
 if test -n "$JAR"; then
-  echo "$as_me:13269: result: $JAR" >&5
+  echo "$as_me:13321: result: $JAR" >&5
 echo "${ECHO_T}$JAR" >&6
 else
-  echo "$as_me:13272: result: no" >&5
+  echo "$as_me:13324: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "javadoc", so it can be a program name with args.
 set dummy javadoc; ac_word=$2
-echo "$as_me:13278: checking for $ac_word" >&5
+echo "$as_me:13330: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_JAVADOC+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13292,7 +13344,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_JAVADOC="$ac_dir/$ac_word"
-   echo "$as_me:13295: found $ac_dir/$ac_word" >&5
+   echo "$as_me:13347: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -13304,16 +13356,16 @@ fi
 JAVADOC=$ac_cv_path_JAVADOC
 
 if test -n "$JAVADOC"; then
-  echo "$as_me:13307: result: $JAVADOC" >&5
+  echo "$as_me:13359: result: $JAVADOC" >&5
 echo "${ECHO_T}$JAVADOC" >&6
 else
-  echo "$as_me:13310: result: no" >&5
+  echo "$as_me:13362: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "jhindexer", so it can be a program name with args.
 set dummy jhindexer; ac_word=$2
-echo "$as_me:13316: checking for $ac_word" >&5
+echo "$as_me:13368: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_JHINDEXER+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13330,7 +13382,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_JHINDEXER="$ac_dir/$ac_word"
-   echo "$as_me:13333: found $ac_dir/$ac_word" >&5
+   echo "$as_me:13385: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -13342,16 +13394,16 @@ fi
 JHINDEXER=$ac_cv_path_JHINDEXER
 
 if test -n "$JHINDEXER"; then
-  echo "$as_me:13345: result: $JHINDEXER" >&5
+  echo "$as_me:13397: result: $JHINDEXER" >&5
 echo "${ECHO_T}$JHINDEXER" >&6
 else
-  echo "$as_me:13348: result: no" >&5
+  echo "$as_me:13400: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "doxygen", so it can be a program name with args.
 set dummy doxygen; ac_word=$2
-echo "$as_me:13354: checking for $ac_word" >&5
+echo "$as_me:13406: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_DOXYGEN+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13368,7 +13420,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_DOXYGEN="$ac_dir/$ac_word"
-   echo "$as_me:13371: found $ac_dir/$ac_word" >&5
+   echo "$as_me:13423: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -13380,16 +13432,16 @@ fi
 DOXYGEN=$ac_cv_path_DOXYGEN
 
 if test -n "$DOXYGEN"; then
-  echo "$as_me:13383: result: $DOXYGEN" >&5
+  echo "$as_me:13435: result: $DOXYGEN" >&5
 echo "${ECHO_T}$DOXYGEN" >&6
 else
-  echo "$as_me:13386: result: no" >&5
+  echo "$as_me:13438: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "dot", so it can be a program name with args.
 set dummy dot; ac_word=$2
-echo "$as_me:13392: checking for $ac_word" >&5
+echo "$as_me:13444: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_HAVE_DOT+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13404,7 +13456,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_HAVE_DOT="YES"
-echo "$as_me:13407: found $ac_dir/$ac_word" >&5
+echo "$as_me:13459: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -13413,10 +13465,10 @@ fi
 fi
 HAVE_DOT=$ac_cv_prog_HAVE_DOT
 if test -n "$HAVE_DOT"; then
-  echo "$as_me:13416: result: $HAVE_DOT" >&5
+  echo "$as_me:13468: result: $HAVE_DOT" >&5
 echo "${ECHO_T}$HAVE_DOT" >&6
 else
-  echo "$as_me:13419: result: no" >&5
+  echo "$as_me:13471: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -13424,7 +13476,7 @@ for ac_prog in browser netscape konqueror mozilla iexplore.exe lynx
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:13427: checking for $ac_word" >&5
+echo "$as_me:13479: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_BROWSER+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13441,7 +13493,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_BROWSER="$ac_dir/$ac_word"
-   echo "$as_me:13444: found $ac_dir/$ac_word" >&5
+   echo "$as_me:13496: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -13452,10 +13504,10 @@ fi
 BROWSER=$ac_cv_path_BROWSER
 
 if test -n "$BROWSER"; then
-  echo "$as_me:13455: result: $BROWSER" >&5
+  echo "$as_me:13507: result: $BROWSER" >&5
 echo "${ECHO_T}$BROWSER" >&6
 else
-  echo "$as_me:13458: result: no" >&5
+  echo "$as_me:13510: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -13465,7 +13517,7 @@ test -n "$BROWSER" || BROWSER="$FALSE"
 
 # Extract the first word of "xref", so it can be a program name with args.
 set dummy xref; ac_word=$2
-echo "$as_me:13468: checking for $ac_word" >&5
+echo "$as_me:13520: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_XREF+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13482,7 +13534,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_XREF="$ac_dir/$ac_word"
-   echo "$as_me:13485: found $ac_dir/$ac_word" >&5
+   echo "$as_me:13537: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -13494,16 +13546,16 @@ fi
 XREF=$ac_cv_path_XREF
 
 if test -n "$XREF"; then
-  echo "$as_me:13497: result: $XREF" >&5
+  echo "$as_me:13549: result: $XREF" >&5
 echo "${ECHO_T}$XREF" >&6
 else
-  echo "$as_me:13500: result: no" >&5
+  echo "$as_me:13552: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 if test "$ac_cv_search_gethostbyname2" = "no"
 then
-  { echo "$as_me:13506: WARNING: you will not be able to resolve IPv6 names" >&5
+  { echo "$as_me:13558: WARNING: you will not be able to resolve IPv6 names" >&5
 echo "$as_me: WARNING: you will not be able to resolve IPv6 names" >&2;}
 fi
 
@@ -13617,7 +13669,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:13620: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:13672: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -13795,7 +13847,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:13798: error: ambiguous option: $1
+    { { echo "$as_me:13850: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -13814,7 +13866,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:13817: error: unrecognized option: $1
+  -*) { { echo "$as_me:13869: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -13852,7 +13904,7 @@ do
   "Make.config" ) CONFIG_FILES="$CONFIG_FILES Make.config" ;;
   "getcwd.sh" ) CONFIG_FILES="$CONFIG_FILES getcwd.sh" ;;
   "libbk_autoconf.h" ) CONFIG_HEADERS="$CONFIG_HEADERS libbk_autoconf.h" ;;
-  *) { { echo "$as_me:13855: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:13907: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -14003,7 +14055,9 @@ s,@GREP@,$GREP,;t t
 s,@AR@,$AR,;t t
 s,@XML2CONFIG@,$XML2CONFIG,;t t
 s,@BGCC@,$BGCC,;t t
+s,@PARASOFT@,$PARASOFT,;t t
 s,@INSURE@,$INSURE,;t t
+s,@JTEST@,$JTEST,;t t
 s,@JAVAC@,$JAVAC,;t t
 s,@JAR@,$JAR,;t t
 s,@JAVADOC@,$JAVADOC,;t t
@@ -14128,7 +14182,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:14131: creating $ac_file" >&5
+    { echo "$as_me:14185: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -14146,7 +14200,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:14149: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:14203: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -14159,7 +14213,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:14162: error: cannot find input file: $f" >&5
+           { { echo "$as_me:14216: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -14220,7 +14274,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:14223: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:14277: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -14231,7 +14285,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:14234: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:14288: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -14244,7 +14298,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:14247: error: cannot find input file: $f" >&5
+           { { echo "$as_me:14301: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -14361,7 +14415,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:14364: $ac_file is unchanged" >&5
+      { echo "$as_me:14418: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
