Xref support.  I *think* I got the autoconf stuff right. :)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.66 .
+# From configure.in Revision: 1.68 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.
 #
@@ -3184,8 +3184,8 @@ fi
 CFLAGS=$HOLD_CFLAGS
 fi
 
-# <TODO>This macro doesn't work right when cross-compiling; it should be
-# replaced by something that greps the generated object file.</TODO>
+# <TODO bugid="999">This macro doesn't work right when cross-compiling; it
+# should be replaced by something that greps the generated object file.</TODO>
 echo "$as_me:3189: checking whether byte ordering is bigendian" >&5
 echo $ECHO_N "checking whether byte ordering is bigendian... $ECHO_C" >&6
 if test "${ac_cv_c_bigendian+set}" = set; then
@@ -12281,9 +12281,47 @@ fi
 done
 test -n "$BROWSER" || BROWSER="$FALSE"
 
+# Extract the first word of "xref", so it can be a program name with args.
+set dummy xref; ac_word=$2
+echo "$as_me:12286: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_XREF+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $XREF in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_XREF="$XREF" # Let the user override the test with a path.
+  ;;
+  *)
+  ac_save_IFS=$IFS; IFS=$ac_path_separator
+ac_dummy="$PATH"
+for ac_dir in $ac_dummy; do
+  IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  if $as_executable_p "$ac_dir/$ac_word"; then
+   ac_cv_path_XREF="$ac_dir/$ac_word"
+   echo "$as_me:12303: found $ac_dir/$ac_word" >&5
+   break
+fi
+done
+
+  test -z "$ac_cv_path_XREF" && ac_cv_path_XREF="$FALSE"
+  ;;
+esac
+fi
+XREF=$ac_cv_path_XREF
+
+if test -n "$XREF"; then
+  echo "$as_me:12315: result: $XREF" >&5
+echo "${ECHO_T}$XREF" >&6
+else
+  echo "$as_me:12318: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
 # Extract the first word of "ar", so it can be a program name with args.
 set dummy ar; ac_word=$2
-echo "$as_me:12286: checking for $ac_word" >&5
+echo "$as_me:12324: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_AR+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -12300,7 +12338,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_AR="$ac_dir/$ac_word"
-   echo "$as_me:12303: found $ac_dir/$ac_word" >&5
+   echo "$as_me:12341: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -12311,16 +12349,16 @@ fi
 AR=$ac_cv_path_AR
 
 if test -n "$AR"; then
-  echo "$as_me:12314: result: $AR" >&5
+  echo "$as_me:12352: result: $AR" >&5
 echo "${ECHO_T}$AR" >&6
 else
-  echo "$as_me:12317: result: no" >&5
+  echo "$as_me:12355: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 if test "$ac_cv_search_gethostbyname2" = "no"
 then
-  { echo "$as_me:12323: WARNING: you will not be able to resolve IPv6 names" >&5
+  { echo "$as_me:12361: WARNING: you will not be able to resolve IPv6 names" >&5
 echo "$as_me: WARNING: you will not be able to resolve IPv6 names" >&2;}
 fi
 
@@ -12411,7 +12449,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:12414: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:12452: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -12589,7 +12627,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:12592: error: ambiguous option: $1
+    { { echo "$as_me:12630: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -12608,7 +12646,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:12611: error: unrecognized option: $1
+  -*) { { echo "$as_me:12649: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -12645,7 +12683,7 @@ do
   # Handling of arguments.
   "Make.config" ) CONFIG_FILES="$CONFIG_FILES Make.config" ;;
   "libbk_autoconf.h" ) CONFIG_HEADERS="$CONFIG_HEADERS libbk_autoconf.h" ;;
-  *) { { echo "$as_me:12648: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:12686: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -12800,6 +12838,7 @@ s,@JHINDEXER@,$JHINDEXER,;t t
 s,@DOXYGEN@,$DOXYGEN,;t t
 s,@HAVE_DOT@,$HAVE_DOT,;t t
 s,@BROWSER@,$BROWSER,;t t
+s,@XREF@,$XREF,;t t
 s,@AR@,$AR,;t t
 CEOF
 
@@ -12915,7 +12954,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:12918: creating $ac_file" >&5
+    { echo "$as_me:12957: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -12933,7 +12972,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:12936: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:12975: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -12946,7 +12985,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:12949: error: cannot find input file: $f" >&5
+           { { echo "$as_me:12988: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -13007,7 +13046,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:13010: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:13049: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -13018,7 +13057,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:13021: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:13060: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -13031,7 +13070,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:13034: error: cannot find input file: $f" >&5
+           { { echo "$as_me:13073: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -13148,7 +13187,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:13151: $ac_file is unchanged" >&5
+      { echo "$as_me:13190: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
