bk route information

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -29264,6 +29264,33 @@ echo "${ECHO_T}no" >&6
 fi
 
 
+echo "$as_me:$LINENO: checking for /proc/net/route" >&5
+echo $ECHO_N "checking for /proc/net/route... $ECHO_C" >&6
+if test "${ac_cv_file__proc_net_route+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "/proc/net/route"; then
+  ac_cv_file__proc_net_route=yes
+else
+  ac_cv_file__proc_net_route=no
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_file__proc_net_route" >&5
+echo "${ECHO_T}$ac_cv_file__proc_net_route" >&6
+if test $ac_cv_file__proc_net_route = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE__PROC_NET_ROUTE 1
+_ACEOF
+
+
+fi
+
+
 if test "$ac_cv_search_gethostbyname2" = "no"
 then
   { echo "$as_me:$LINENO: WARNING: you will not be able to resolve IPv6 names" >&5
