autoconf existence of /dev/fd filesystem.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.62 .
+# From configure.in Revision: 1.63 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.
 #
@@ -12110,9 +12110,33 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+echo "$as_me:12113: checking for /dev/fd/0" >&5
+echo $ECHO_N "checking for /dev/fd/0... $ECHO_C" >&6
+if test "${ac_cv_file__dev_fd_0+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:12119: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "/dev/fd/0"; then
+  ac_cv_file__dev_fd_0=yes
+else
+  ac_cv_file__dev_fd_0=no
+fi
+fi
+echo "$as_me:12128: result: $ac_cv_file__dev_fd_0" >&5
+echo "${ECHO_T}$ac_cv_file__dev_fd_0" >&6
+if test $ac_cv_file__dev_fd_0 = yes; then
+  cat >>confdefs.h <<\EOF
+#define HAVE_DEVFD 1
+EOF
+
+fi
+
 if test "$ac_cv_search_gethostbyname2" = "no"
 then
-  { echo "$as_me:12115: WARNING: you will only be able to resolve AF_INET names" >&5
+  { echo "$as_me:12139: WARNING: you will only be able to resolve AF_INET names" >&5
 echo "$as_me: WARNING: you will only be able to resolve AF_INET names" >&2;}
 fi
 
@@ -12203,7 +12227,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:12206: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:12230: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -12381,7 +12405,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:12384: error: ambiguous option: $1
+    { { echo "$as_me:12408: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -12400,7 +12424,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:12403: error: unrecognized option: $1
+  -*) { { echo "$as_me:12427: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -12437,7 +12461,7 @@ do
   # Handling of arguments.
   "Make.config" ) CONFIG_FILES="$CONFIG_FILES Make.config" ;;
   "libbk_autoconf.h" ) CONFIG_HEADERS="$CONFIG_HEADERS libbk_autoconf.h" ;;
-  *) { { echo "$as_me:12440: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:12464: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -12703,7 +12727,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:12706: creating $ac_file" >&5
+    { echo "$as_me:12730: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -12721,7 +12745,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:12724: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:12748: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -12734,7 +12758,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:12737: error: cannot find input file: $f" >&5
+           { { echo "$as_me:12761: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -12795,7 +12819,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:12798: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:12822: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -12806,7 +12830,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:12809: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:12833: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -12819,7 +12843,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:12822: error: cannot find input file: $f" >&5
+           { { echo "$as_me:12846: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -12936,7 +12960,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:12939: $ac_file is unchanged" >&5
+      { echo "$as_me:12963: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
