Use profilingly libs when avaialble. Fix compiling when using WANT_GPROF=true.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12635,9 +12635,47 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+# Extract the first word of "grep", so it can be a program name with args.
+set dummy grep; ac_word=$2
+echo "$as_me:12640: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_GREP+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $GREP in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_GREP="$GREP" # Let the user override the test with a path.
+  ;;
+  *)
+  ac_save_IFS=$IFS; IFS=$ac_path_separator
+ac_dummy="$PATH"
+for ac_dir in $ac_dummy; do
+  IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  if $as_executable_p "$ac_dir/$ac_word"; then
+   ac_cv_path_GREP="$ac_dir/$ac_word"
+   echo "$as_me:12657: found $ac_dir/$ac_word" >&5
+   break
+fi
+done
+
+  test -z "$ac_cv_path_GREP" && ac_cv_path_GREP="$FALSE"
+  ;;
+esac
+fi
+GREP=$ac_cv_path_GREP
+
+if test -n "$GREP"; then
+  echo "$as_me:12669: result: $GREP" >&5
+echo "${ECHO_T}$GREP" >&6
+else
+  echo "$as_me:12672: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
 # Extract the first word of "ar", so it can be a program name with args.
 set dummy ar; ac_word=$2
-echo "$as_me:12640: checking for $ac_word" >&5
+echo "$as_me:12678: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_AR+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -12654,7 +12692,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_AR="$ac_dir/$ac_word"
-   echo "$as_me:12657: found $ac_dir/$ac_word" >&5
+   echo "$as_me:12695: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -12665,16 +12703,16 @@ fi
 AR=$ac_cv_path_AR
 
 if test -n "$AR"; then
-  echo "$as_me:12668: result: $AR" >&5
+  echo "$as_me:12706: result: $AR" >&5
 echo "${ECHO_T}$AR" >&6
 else
-  echo "$as_me:12671: result: no" >&5
+  echo "$as_me:12709: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "xml2-config", so it can be a program name with args.
 set dummy xml2-config; ac_word=$2
-echo "$as_me:12677: checking for $ac_word" >&5
+echo "$as_me:12715: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_XML2CONFIG+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -12691,7 +12729,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_XML2CONFIG="$ac_dir/$ac_word"
-   echo "$as_me:12694: found $ac_dir/$ac_word" >&5
+   echo "$as_me:12732: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -12703,17 +12741,17 @@ fi
 XML2CONFIG=$ac_cv_path_XML2CONFIG
 
 if test -n "$XML2CONFIG"; then
-  echo "$as_me:12706: result: $XML2CONFIG" >&5
+  echo "$as_me:12744: result: $XML2CONFIG" >&5
 echo "${ECHO_T}$XML2CONFIG" >&6
 else
-  echo "$as_me:12709: result: no" >&5
+  echo "$as_me:12747: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # not everybody puts /usr/local/gnu/bin in their PATH
 # Extract the first word of "bgcc", so it can be a program name with args.
 set dummy bgcc; ac_word=$2
-echo "$as_me:12716: checking for $ac_word" >&5
+echo "$as_me:12754: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_BGCC+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -12730,7 +12768,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_BGCC="$ac_dir/$ac_word"
-   echo "$as_me:12733: found $ac_dir/$ac_word" >&5
+   echo "$as_me:12771: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -12742,16 +12780,16 @@ fi
 BGCC=$ac_cv_path_BGCC
 
 if test -n "$BGCC"; then
-  echo "$as_me:12745: result: $BGCC" >&5
+  echo "$as_me:12783: result: $BGCC" >&5
 echo "${ECHO_T}$BGCC" >&6
 else
-  echo "$as_me:12748: result: no" >&5
+  echo "$as_me:12786: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "insure", so it can be a program name with args.
 set dummy insure; ac_word=$2
-echo "$as_me:12754: checking for $ac_word" >&5
+echo "$as_me:12792: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_INSURE+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -12768,7 +12806,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_INSURE="$ac_dir/$ac_word"
-   echo "$as_me:12771: found $ac_dir/$ac_word" >&5
+   echo "$as_me:12809: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -12780,10 +12818,10 @@ fi
 INSURE=$ac_cv_path_INSURE
 
 if test -n "$INSURE"; then
-  echo "$as_me:12783: result: $INSURE" >&5
+  echo "$as_me:12821: result: $INSURE" >&5
 echo "${ECHO_T}$INSURE" >&6
 else
-  echo "$as_me:12786: result: no" >&5
+  echo "$as_me:12824: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -12791,7 +12829,7 @@ fi
 
 # Extract the first word of "javac", so it can be a program name with args.
 set dummy javac; ac_word=$2
-echo "$as_me:12794: checking for $ac_word" >&5
+echo "$as_me:12832: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_JAVAC+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -12808,7 +12846,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_JAVAC="$ac_dir/$ac_word"
-   echo "$as_me:12811: found $ac_dir/$ac_word" >&5
+   echo "$as_me:12849: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -12820,16 +12858,16 @@ fi
 JAVAC=$ac_cv_path_JAVAC
 
 if test -n "$JAVAC"; then
-  echo "$as_me:12823: result: $JAVAC" >&5
+  echo "$as_me:12861: result: $JAVAC" >&5
 echo "${ECHO_T}$JAVAC" >&6
 else
-  echo "$as_me:12826: result: no" >&5
+  echo "$as_me:12864: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "jar", so it can be a program name with args.
 set dummy jar; ac_word=$2
-echo "$as_me:12832: checking for $ac_word" >&5
+echo "$as_me:12870: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_JAR+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -12846,7 +12884,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_JAR="$ac_dir/$ac_word"
-   echo "$as_me:12849: found $ac_dir/$ac_word" >&5
+   echo "$as_me:12887: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -12858,16 +12896,16 @@ fi
 JAR=$ac_cv_path_JAR
 
 if test -n "$JAR"; then
-  echo "$as_me:12861: result: $JAR" >&5
+  echo "$as_me:12899: result: $JAR" >&5
 echo "${ECHO_T}$JAR" >&6
 else
-  echo "$as_me:12864: result: no" >&5
+  echo "$as_me:12902: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "jhindexer", so it can be a program name with args.
 set dummy jhindexer; ac_word=$2
-echo "$as_me:12870: checking for $ac_word" >&5
+echo "$as_me:12908: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_JHINDEXER+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -12884,7 +12922,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_JHINDEXER="$ac_dir/$ac_word"
-   echo "$as_me:12887: found $ac_dir/$ac_word" >&5
+   echo "$as_me:12925: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -12896,16 +12934,16 @@ fi
 JHINDEXER=$ac_cv_path_JHINDEXER
 
 if test -n "$JHINDEXER"; then
-  echo "$as_me:12899: result: $JHINDEXER" >&5
+  echo "$as_me:12937: result: $JHINDEXER" >&5
 echo "${ECHO_T}$JHINDEXER" >&6
 else
-  echo "$as_me:12902: result: no" >&5
+  echo "$as_me:12940: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "doxygen", so it can be a program name with args.
 set dummy doxygen; ac_word=$2
-echo "$as_me:12908: checking for $ac_word" >&5
+echo "$as_me:12946: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_DOXYGEN+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -12922,7 +12960,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_DOXYGEN="$ac_dir/$ac_word"
-   echo "$as_me:12925: found $ac_dir/$ac_word" >&5
+   echo "$as_me:12963: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -12934,16 +12972,16 @@ fi
 DOXYGEN=$ac_cv_path_DOXYGEN
 
 if test -n "$DOXYGEN"; then
-  echo "$as_me:12937: result: $DOXYGEN" >&5
+  echo "$as_me:12975: result: $DOXYGEN" >&5
 echo "${ECHO_T}$DOXYGEN" >&6
 else
-  echo "$as_me:12940: result: no" >&5
+  echo "$as_me:12978: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "dot", so it can be a program name with args.
 set dummy dot; ac_word=$2
-echo "$as_me:12946: checking for $ac_word" >&5
+echo "$as_me:12984: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_HAVE_DOT+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -12958,7 +12996,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_HAVE_DOT="YES"
-echo "$as_me:12961: found $ac_dir/$ac_word" >&5
+echo "$as_me:12999: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -12967,10 +13005,10 @@ fi
 fi
 HAVE_DOT=$ac_cv_prog_HAVE_DOT
 if test -n "$HAVE_DOT"; then
-  echo "$as_me:12970: result: $HAVE_DOT" >&5
+  echo "$as_me:13008: result: $HAVE_DOT" >&5
 echo "${ECHO_T}$HAVE_DOT" >&6
 else
-  echo "$as_me:12973: result: no" >&5
+  echo "$as_me:13011: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -12978,7 +13016,7 @@ for ac_prog in browser netscape konqueror mozilla iexplore.exe lynx
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:12981: checking for $ac_word" >&5
+echo "$as_me:13019: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_BROWSER+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -12995,7 +13033,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_BROWSER="$ac_dir/$ac_word"
-   echo "$as_me:12998: found $ac_dir/$ac_word" >&5
+   echo "$as_me:13036: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -13006,10 +13044,10 @@ fi
 BROWSER=$ac_cv_path_BROWSER
 
 if test -n "$BROWSER"; then
-  echo "$as_me:13009: result: $BROWSER" >&5
+  echo "$as_me:13047: result: $BROWSER" >&5
 echo "${ECHO_T}$BROWSER" >&6
 else
-  echo "$as_me:13012: result: no" >&5
+  echo "$as_me:13050: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -13019,7 +13057,7 @@ test -n "$BROWSER" || BROWSER="$FALSE"
 
 # Extract the first word of "xref", so it can be a program name with args.
 set dummy xref; ac_word=$2
-echo "$as_me:13022: checking for $ac_word" >&5
+echo "$as_me:13060: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_XREF+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13036,7 +13074,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_XREF="$ac_dir/$ac_word"
-   echo "$as_me:13039: found $ac_dir/$ac_word" >&5
+   echo "$as_me:13077: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -13048,16 +13086,16 @@ fi
 XREF=$ac_cv_path_XREF
 
 if test -n "$XREF"; then
-  echo "$as_me:13051: result: $XREF" >&5
+  echo "$as_me:13089: result: $XREF" >&5
 echo "${ECHO_T}$XREF" >&6
 else
-  echo "$as_me:13054: result: no" >&5
+  echo "$as_me:13092: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 if test "$ac_cv_search_gethostbyname2" = "no"
 then
-  { echo "$as_me:13060: WARNING: you will not be able to resolve IPv6 names" >&5
+  { echo "$as_me:13098: WARNING: you will not be able to resolve IPv6 names" >&5
 echo "$as_me: WARNING: you will not be able to resolve IPv6 names" >&2;}
 fi
 
@@ -13171,7 +13209,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:13174: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:13212: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -13349,7 +13387,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:13352: error: ambiguous option: $1
+    { { echo "$as_me:13390: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -13368,7 +13406,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:13371: error: unrecognized option: $1
+  -*) { { echo "$as_me:13409: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -13406,7 +13444,7 @@ do
   "Make.config" ) CONFIG_FILES="$CONFIG_FILES Make.config" ;;
   "getcwd.sh" ) CONFIG_FILES="$CONFIG_FILES getcwd.sh" ;;
   "libbk_autoconf.h" ) CONFIG_HEADERS="$CONFIG_HEADERS libbk_autoconf.h" ;;
-  *) { { echo "$as_me:13409: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:13447: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -13550,6 +13588,7 @@ s,@CAT@,$CAT,;t t
 s,@BASENAME@,$BASENAME,;t t
 s,@SED@,$SED,;t t
 s,@PERL@,$PERL,;t t
+s,@GREP@,$GREP,;t t
 s,@AR@,$AR,;t t
 s,@XML2CONFIG@,$XML2CONFIG,;t t
 s,@BGCC@,$BGCC,;t t
@@ -13677,7 +13716,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:13680: creating $ac_file" >&5
+    { echo "$as_me:13719: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -13695,7 +13734,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:13698: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:13737: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -13708,7 +13747,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:13711: error: cannot find input file: $f" >&5
+           { { echo "$as_me:13750: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -13769,7 +13808,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:13772: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:13811: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -13780,7 +13819,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:13783: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:13822: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -13793,7 +13832,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:13796: error: cannot find input file: $f" >&5
+           { { echo "$as_me:13835: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -13910,7 +13949,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:13913: $ac_file is unchanged" >&5
+      { echo "$as_me:13952: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
