RedHat 9 java port issues (must prefer /usr/local/java over /usr/bin)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.72 .
+# From configure.in Revision: 1.73 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.
 #
@@ -12827,9 +12827,12 @@ fi
 
 # note - don't use $PATH_SEPARATOR in this file; we always use Cygwin make
 
+# Note RedHat 9 has a non-Sun Java in /usr/bin, so /usr/local should
+# be prefixed.  This doesn't allow any way to override the system
+# default for new version testing, though...
 # Extract the first word of "javac", so it can be a program name with args.
 set dummy javac; ac_word=$2
-echo "$as_me:12832: checking for $ac_word" >&5
+echo "$as_me:12835: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_JAVAC+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -12840,13 +12843,13 @@ else
   ;;
   *)
   ac_save_IFS=$IFS; IFS=$ac_path_separator
-ac_dummy="$PATH:/usr/java/jdk/bin:/usr/local/java/jdk/bin"
+ac_dummy="/usr/local/java/jdk/bin:$PATH:/usr/java/jdk/bin"
 for ac_dir in $ac_dummy; do
   IFS=$ac_save_IFS
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_JAVAC="$ac_dir/$ac_word"
-   echo "$as_me:12849: found $ac_dir/$ac_word" >&5
+   echo "$as_me:12852: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -12858,16 +12861,16 @@ fi
 JAVAC=$ac_cv_path_JAVAC
 
 if test -n "$JAVAC"; then
-  echo "$as_me:12861: result: $JAVAC" >&5
+  echo "$as_me:12864: result: $JAVAC" >&5
 echo "${ECHO_T}$JAVAC" >&6
 else
-  echo "$as_me:12864: result: no" >&5
+  echo "$as_me:12867: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "jar", so it can be a program name with args.
 set dummy jar; ac_word=$2
-echo "$as_me:12870: checking for $ac_word" >&5
+echo "$as_me:12873: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_JAR+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -12878,13 +12881,13 @@ else
   ;;
   *)
   ac_save_IFS=$IFS; IFS=$ac_path_separator
-ac_dummy="$PATH:/usr/java/jdk/bin:/usr/local/java/jdk/bin"
+ac_dummy="/usr/local/java/jdk/bin:$PATH:/usr/java/jdk/bin"
 for ac_dir in $ac_dummy; do
   IFS=$ac_save_IFS
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_JAR="$ac_dir/$ac_word"
-   echo "$as_me:12887: found $ac_dir/$ac_word" >&5
+   echo "$as_me:12890: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -12896,16 +12899,16 @@ fi
 JAR=$ac_cv_path_JAR
 
 if test -n "$JAR"; then
-  echo "$as_me:12899: result: $JAR" >&5
+  echo "$as_me:12902: result: $JAR" >&5
 echo "${ECHO_T}$JAR" >&6
 else
-  echo "$as_me:12902: result: no" >&5
+  echo "$as_me:12905: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "jhindexer", so it can be a program name with args.
 set dummy jhindexer; ac_word=$2
-echo "$as_me:12908: checking for $ac_word" >&5
+echo "$as_me:12911: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_JHINDEXER+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -12916,13 +12919,13 @@ else
   ;;
   *)
   ac_save_IFS=$IFS; IFS=$ac_path_separator
-ac_dummy="$PATH:/usr/local/java/bin"
+ac_dummy="/usr/local/java/bin:$PATH"
 for ac_dir in $ac_dummy; do
   IFS=$ac_save_IFS
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_JHINDEXER="$ac_dir/$ac_word"
-   echo "$as_me:12925: found $ac_dir/$ac_word" >&5
+   echo "$as_me:12928: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -12934,16 +12937,16 @@ fi
 JHINDEXER=$ac_cv_path_JHINDEXER
 
 if test -n "$JHINDEXER"; then
-  echo "$as_me:12937: result: $JHINDEXER" >&5
+  echo "$as_me:12940: result: $JHINDEXER" >&5
 echo "${ECHO_T}$JHINDEXER" >&6
 else
-  echo "$as_me:12940: result: no" >&5
+  echo "$as_me:12943: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "doxygen", so it can be a program name with args.
 set dummy doxygen; ac_word=$2
-echo "$as_me:12946: checking for $ac_word" >&5
+echo "$as_me:12949: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_DOXYGEN+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -12960,7 +12963,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_DOXYGEN="$ac_dir/$ac_word"
-   echo "$as_me:12963: found $ac_dir/$ac_word" >&5
+   echo "$as_me:12966: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -12972,16 +12975,16 @@ fi
 DOXYGEN=$ac_cv_path_DOXYGEN
 
 if test -n "$DOXYGEN"; then
-  echo "$as_me:12975: result: $DOXYGEN" >&5
+  echo "$as_me:12978: result: $DOXYGEN" >&5
 echo "${ECHO_T}$DOXYGEN" >&6
 else
-  echo "$as_me:12978: result: no" >&5
+  echo "$as_me:12981: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 # Extract the first word of "dot", so it can be a program name with args.
 set dummy dot; ac_word=$2
-echo "$as_me:12984: checking for $ac_word" >&5
+echo "$as_me:12987: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_HAVE_DOT+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -12996,7 +12999,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_HAVE_DOT="YES"
-echo "$as_me:12999: found $ac_dir/$ac_word" >&5
+echo "$as_me:13002: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -13005,10 +13008,10 @@ fi
 fi
 HAVE_DOT=$ac_cv_prog_HAVE_DOT
 if test -n "$HAVE_DOT"; then
-  echo "$as_me:13008: result: $HAVE_DOT" >&5
+  echo "$as_me:13011: result: $HAVE_DOT" >&5
 echo "${ECHO_T}$HAVE_DOT" >&6
 else
-  echo "$as_me:13011: result: no" >&5
+  echo "$as_me:13014: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -13016,7 +13019,7 @@ for ac_prog in browser netscape konqueror mozilla iexplore.exe lynx
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:13019: checking for $ac_word" >&5
+echo "$as_me:13022: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_BROWSER+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13033,7 +13036,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_BROWSER="$ac_dir/$ac_word"
-   echo "$as_me:13036: found $ac_dir/$ac_word" >&5
+   echo "$as_me:13039: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -13044,10 +13047,10 @@ fi
 BROWSER=$ac_cv_path_BROWSER
 
 if test -n "$BROWSER"; then
-  echo "$as_me:13047: result: $BROWSER" >&5
+  echo "$as_me:13050: result: $BROWSER" >&5
 echo "${ECHO_T}$BROWSER" >&6
 else
-  echo "$as_me:13050: result: no" >&5
+  echo "$as_me:13053: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -13057,7 +13060,7 @@ test -n "$BROWSER" || BROWSER="$FALSE"
 
 # Extract the first word of "xref", so it can be a program name with args.
 set dummy xref; ac_word=$2
-echo "$as_me:13060: checking for $ac_word" >&5
+echo "$as_me:13063: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_XREF+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -13074,7 +13077,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_XREF="$ac_dir/$ac_word"
-   echo "$as_me:13077: found $ac_dir/$ac_word" >&5
+   echo "$as_me:13080: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -13086,16 +13089,16 @@ fi
 XREF=$ac_cv_path_XREF
 
 if test -n "$XREF"; then
-  echo "$as_me:13089: result: $XREF" >&5
+  echo "$as_me:13092: result: $XREF" >&5
 echo "${ECHO_T}$XREF" >&6
 else
-  echo "$as_me:13092: result: no" >&5
+  echo "$as_me:13095: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 if test "$ac_cv_search_gethostbyname2" = "no"
 then
-  { echo "$as_me:13098: WARNING: you will not be able to resolve IPv6 names" >&5
+  { echo "$as_me:13101: WARNING: you will not be able to resolve IPv6 names" >&5
 echo "$as_me: WARNING: you will not be able to resolve IPv6 names" >&2;}
 fi
 
@@ -13209,7 +13212,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:13212: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:13215: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -13387,7 +13390,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:13390: error: ambiguous option: $1
+    { { echo "$as_me:13393: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -13406,7 +13409,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:13409: error: unrecognized option: $1
+  -*) { { echo "$as_me:13412: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -13444,7 +13447,7 @@ do
   "Make.config" ) CONFIG_FILES="$CONFIG_FILES Make.config" ;;
   "getcwd.sh" ) CONFIG_FILES="$CONFIG_FILES getcwd.sh" ;;
   "libbk_autoconf.h" ) CONFIG_HEADERS="$CONFIG_HEADERS libbk_autoconf.h" ;;
-  *) { { echo "$as_me:13447: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:13450: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -13716,7 +13719,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:13719: creating $ac_file" >&5
+    { echo "$as_me:13722: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -13734,7 +13737,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:13737: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:13740: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -13747,7 +13750,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:13750: error: cannot find input file: $f" >&5
+           { { echo "$as_me:13753: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -13808,7 +13811,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:13811: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:13814: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -13819,7 +13822,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:13822: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:13825: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -13832,7 +13835,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:13835: error: cannot find input file: $f" >&5
+           { { echo "$as_me:13838: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -13949,7 +13952,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:13952: $ac_file is unchanged" >&5
+      { echo "$as_me:13955: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
